### ISSUE TITLE
Error while trying to run it

### ISSUE THREAD

**Issue by franciscop** [yamafaktory/shrimpit#104]
When trying to run it with any command I get this error:

```bash
 Shrimpit!  

(node:9578) UnhandledPromiseRejectionWarning: TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/node_modules/dir-glob/index.js:48:25)
    at globDirs (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/node_modules/globby/index.js:58:9)
    at getPattern (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/node_modules/globby/index.js:61:64)
    at Promise.all.globTasks.map.task (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/node_modules/globby/index.js:72:69)
    at Array.map (<anonymous>)
    at module.exports (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/node_modules/globby/index.js:72:41)
    at Shrimpit.exec (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/lib.js:126:25)
    at Object.<anonymous> (/home/francisco/.nvm/versions/node/v11.3.0/lib/node_modules/shrimpit/index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
(node:9578) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9578) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I just installed `shrimpit` with `npm install shrimpit -g` in Ubuntu 18.04. My Node.js version is `v11.3.0`.

**Comment by franciscop** [comment]
Steps to reproduce:

1. Open [RunKit](https://npm.runkit.com/shrimpit) for browser Node.js testing.
2. Put this code, run it and wait a couple of seconds until it's run:

```js
var Shrimpit = require("shrimpit/lib");
const shrimpit = new Shrimpit(['', '', 'index.js']);
shrimpit.exec();
module.exports = { a: 'b' };
```

**Comment by yamafaktory** [comment]
@franciscop thanks for the report! I'll have a look at it.

**Comment by yamafaktory** [comment]
@franciscop this an issue coming from one of the dependencies, see https://github.com/sindresorhus/globby/issues/106. I'm going to release a new version this week for another reason and this should be fixed too. I'll keep you updated!
