### ISSUE TITLE
namespace-imports TypeError

### ISSUE THREAD

**Issue by ldstein** [yamafaktory/shrimpit#113]
Hi, 

I'm getting a TypeError when running shrimpit on ES6 Modules which use wilcard import statements.

```
import * as foods from './food-types'
...
```

System:
- Windows 10 x64
- Node v10.15.1
- shrimpit@1.1.0

Step to recreate:
```
npm install shrimpit -g
shrimpit /users/ldstein/AppData/Roaming/npm/node_modules/shrimpit/test/namespace-imports/b.js
```
Output is:
```
(node:9872) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `imports` of 'undefined' or 'null'.
    at namespaceImports.map (C:\Users\ldstein\AppData\Roaming\npm\node_modules\shrimpit\lib.js:318:41)
    at Array.map (<anonymous>)
    at Shrimpit.resolveNamespaceImports (C:\Users\ldstein\AppData\Roaming\npm\node_modules\shrimpit\lib.js:317:27)
    at Shrimpit.exec (C:\Users\ldstein\AppData\Roaming\npm\node_modules\shrimpit\lib.js:142:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Anyone else able to confirm if they are seeing the same behaviour?

**Comment by yamafaktory** [comment]
Hi @ldstein ✋. This should have been addressed in the latest version 🚀.
